# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Git-backed collaborative memory ledger for coding agents"
  homepage "https://github.com/AndreasSteinerPF/team-memory"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.6.0/tm_0.6.0_darwin_amd64.tar.gz"
      sha256 "69733830879ea7971dbed182a312da434d569ecd25b1f6e25ff813c69b857ac7"

      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.6.0/tm_0.6.0_darwin_arm64.tar.gz"
      sha256 "8142275ea54dcd3e1ebe91c74c900ea8f4c8116b507e16a6f81cf9711dfcf3cf"

      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.6.0/tm_0.6.0_linux_amd64.tar.gz"
      sha256 "806d2f281de8da1e60b61c116ce38d02531d68908307eaf7f8414d0f1100c554"
      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.6.0/tm_0.6.0_linux_arm64.tar.gz"
      sha256 "9e6848ed67b02e3ad06fdda8982e9143406a6cfe855c70d64f665602651d8489"
      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  test do
    system "#{bin}/tm", "version"
  end
end
