# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Git-backed collaborative memory ledger for coding agents"
  homepage "https://github.com/AndreasSteinerPF/team-memory"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.6.1/tm_0.6.1_darwin_amd64.tar.gz"
      sha256 "cb38a1e611ae3657969e6b89be1f47b0e4f235834155afa6ec74ab5f7267fef9"

      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.6.1/tm_0.6.1_darwin_arm64.tar.gz"
      sha256 "f23d2d9b0fd8a1b5cd660db07202f4bdc770d0f1fc105616538126993f4936c1"

      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.6.1/tm_0.6.1_linux_amd64.tar.gz"
      sha256 "1ead0cc606d20a64799abe5c8c72b762f3d633b494efa2538378c738f455a878"
      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.6.1/tm_0.6.1_linux_arm64.tar.gz"
      sha256 "71eb573d03df7d79db1728f1cfa29eeab4759c07693e45813573f1be427a9c5c"
      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  test do
    system "#{bin}/tm", "version"
  end
end
