# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Git-backed collaborative memory ledger for coding agents"
  homepage "https://github.com/AndreasSteinerPF/team-memory"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.7.1/tm_0.7.1_darwin_amd64.tar.gz"
      sha256 "61e1436db11c30447a854e68f17547b5feb64b7bf4bd55d821fbf09c551b1295"

      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.7.1/tm_0.7.1_darwin_arm64.tar.gz"
      sha256 "63b25f69c54b4d386adac58ca62369e006a8dec254351e8f96e7a4f33102226a"

      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.7.1/tm_0.7.1_linux_amd64.tar.gz"
      sha256 "ec2a78841b9e901229584def08938a482857bd8af453677224ac6bb3c1c79e08"
      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreasSteinerPF/team-memory/releases/download/v0.7.1/tm_0.7.1_linux_arm64.tar.gz"
      sha256 "603d0f7a67879059ab2b5436c10409898c3f0de96ce3094a0e8a612e042652e5"
      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  test do
    system "#{bin}/tm", "version"
  end
end
